# markdown

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown', 'md']
hook_add = '''
    autocmd BufRead,BufNewFile *.mkd  set filetype=markdown
    autocmd BufRead,BufNewFile *.md  set filetype=markdown

    hi link htmlItalic LineNr
    hi link htmlBold WarningMsg
    hi link htmlBoldItalic ErrorMsg

    let g:vim_markdown_folding_disabled = 1
    let g:vim_markdown_emphasis_multiline = 1
    let g:vim_markdown_conceal = 0

    let g:vim_markdown_frontmatter = 1
    let g:vim_markdown_toml_frontmatter = 1
    let g:vim_markdown_json_frontmatter = 1
'''

[[plugins]]
repo = 'kannokanno/previm'
hook_add = '''
    let g:previm_enable_realtime = 1
    let g:previm_open_cmd = 'open -a Safari'
    let g:previm_disable_default_css = 1
    let g:previm_custom_css_path = '$HOME/dotfiles/templates/previm/gfm.css'
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
