[[plugins]]
repo = 'zchee/deoplete-jedi'
on_i = 1
on_ft = ['python', 'py']
hook_add = '''
    let g:jedi#popup_on_dot = 1
    let g:jedi#documentation_command = 'K'
    let g:jedi#usage_command = '<leader>n'
    let g:jedi#rename_command = '<leader>R'
    let g:deoplete#sources#jedi#server_timeout = 60
    autocmd FileType python setlocal completeopt-=preview
'''

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python', 'py']
