# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'tmux-plugins/tmux-yank'

### Settings

# tmux status line refresh rate
set -g status-interval 1

# auto rename window
set-window-option -g automatic-rename on

# Force to use 256 colors in tmux
#set -g default-terminal   'xterm-256color'
#set -g terminal-overrides 'xterm:colors=256'

set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# Window index from 1
set -g base-index 1

# Pane Index from 1
setw -g pane-base-index 1

# prefix Ctrl-s
set-option -g prefix C-a
bind-key C-a send-prefix
unbind-key C-b

# use vi bind
setw -g mode-keys vi

# fix Esc key delay time for Vim
set -sg escape-time 0

# mouse on
set-option -g mouse on
bind -n WheelUpPane   select-pane -t= \; copy-mode -e \; send-keys -M
bind -n WheelDownPane select-pane -t= \; send-keys -M
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"
# visual activity
setw -g monitor-activity on
set  -g visual-activity on

### Status Line

# Display Statusbar upperside
set -g status-position top

# statusbar color
set -g status-fg white
set -g status-bg black

# window list color
setw -g window-status-fg white
setw -g window-status-bg default
setw -g window-status-attr dim

# remarkable active window
setw -g window-status-current-fg black
setw -g window-status-current-bg green
setw -g window-status-current-attr bright

# pain color
set -g pane-border-fg white
set -g pane-active-border-fg green

# commandline color
set -g message-fg white
set -g message-bg black
set -g message-attr bright

# left panel
set -g status-left-length 40
set -g status-left "#[fg=cyan]S:#S #[fg=colour3]W:#I #[fg=green]P:#P"

# right panel
set -g status-right-length 80
set -g status-right "#[fg=cyan][%Y-%m-%d(%a) %H:%M:%S]"

# window list justify center
set -g status-justify centre

### Status Line
set-option -g default-command "which reattach-to-user-namespace > /dev/null && reattach-to-user-namespace -l $SHELL || $SHELL"

#####
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

