# denite

## denite
[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
on_event = 'BufRead'
hook_add = '''
    call denite#custom#option('default', 'prompt', '>')

    nmap <silent> <C-d><C-t> :<C-u>Denite filetype<CR>
    nmap <silent> <C-d><C-p> :<C-u>Denite file_rec<CR>
    nmap <silent> <C-d><C-j> :<C-u>Denite line<CR>
    nmap <silent> <C-d><C-g> :<C-u>Denite grep<CR>
    nmap <silent> <C-d><C-]> :<C-u>DeniteCursorWord grep<CR>
    nmap <silent> <C-d><C-u> :<C-u>Denite file_mru<CR>
    nmap <silent> <C-d><C-y> :<C-u>Denite neoyank<CR>
    nmap <silent> <C-d><C-r> :<C-u>Denite -resume<CR>
    nmap <silent> <C-d>; :<C-u>Denite -resume -immediately -select=+1<CR>
    nmap <silent> <C-d>- :<C-u>Denite -resume -immediately -select=-1<CR>
    nmap <silent> <C-d><C-d> :<C-u>call denite#start([{'name': 'file_rec', 'args': ['~/dotfiles']}])<CR>

    call denite#custom#map('insert', "<C-j>", '<denite:move_to_next_line>')
    call denite#custom#map('insert', "<C-k>", '<denite:move_to_previous_line>')
    call denite#custom#map('insert', "<C-t>", '<denite:do_action:tabopen>')
    call denite#custom#map('insert', "<C-v>", '<denite:do_action:vsplit>')
    call denite#custom#map('normal', "v", '<denite:do_action:vsplit>')
    call denite#custom#map('insert', 'jj', '<denite:enter_mode:normal>')
    call denite#custom#source('file_rec', 'matchers', ['matcher_fuzzy','matcher_ignore_globs'])
    call denite#custom#filter('matcher_ignore_globs', 'ignore_globs',
        \ [
        \ '.git/', 'build/', '__pycache__/',
        \ 'images/', '*.o', '*.make',
        \ '*.min.*',
        \ 'img/', 'fonts/'])
'''
hook_post_source = '''
    call denite#custom#var('file_rec', 'command',
        \ ['pt', '--follow', '--nocolor', '--nogroup', '--hidden', '-g', ''])
    call denite#custom#var('grep', 'command',
        \ ['pt', '--nogroup', '--nocolor', '--smart-case', '--hidden'])
    call denite#custom#var('grep', 'default_opts', [])
    call denite#custom#var('grep', 'recursive_opts', [])
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
