# operation

## comment in/out
[[plugins]]
repo = 'tomtom/tcomment_vim'

## auto insert pairs
[[plugins]]
repo = 'cohama/lexima.vim'
hook_add = '''
    call lexima#add_rule({'at': '\%#.*[-0-9a-zA-Z_,:]', 'char': '{', 'input': '{'})
    call lexima#add_rule({'at': '\%#\n\s*}', 'char': '}', 'input': '}', 'delete': '}'})
'''