# quickrun

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
    let g:quickrun_no_default_key_mappings = 1
    nmap <Leader>r :cclose<CR>:write<CR>:QuickRun -mode n<CR>
    nnoremap <expr><silent> <C-c> quickrun#is_running() ? quickrun#sweep_sessions() : "\<C-c>"
    au FileType qf nnoremap <silent><buffer>q :quit<CR>
    let g:quickrun_config = get(g:, 'quickrun_config', {})
    let g:quickrun_config._ = {
      \ 'runner'    : 'vimproc',
      \ 'runner/vimproc/updatetime' : 60,
      \ 'outputter' : 'error',
      \ 'outputter/error/success' : 'buffer',
      \ 'outputter/error/error'   : 'quickfix',
      \ 'outputter/buffer/split'  : ':rightbelow 8sp',
      \ 'outputter/buffer/close_on_empty' : 1,
      \ }
    let g:quickrun_config={'*': {'split': 'vertical'}}
'''
hook_post_update = '''
    let g:quickrun_config = {'*': {'hook/time/enable': '1'},}
'''
