"$schema" = 'https://starship.rs/config-schema.json'
command_timeout = 1000

format = "$os$directory$git_branch$git_status$c$rust$golang$nodejs$php$java$kotlin$haskell$python$docker_context$time$line_break$character"

palette = 'hacker'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[palettes.hacker]
hacker_fg = '#5CB06C'
hacker_bg = '#081208'
hacker_bg_alt = '#061006'
hacker_bg_light = '#0A1808'
hacker_green = '#2A8A2A'
hacker_green_bright = '#4A9A4A'
hacker_cyan = '#308585'
hacker_cyan_bright = '#409090'
hacker_blue = '#407C8D'
hacker_blue_bright = '#6090B0'
hacker_yellow = '#8A8A2A'
hacker_yellow_bright = '#A0A02A'
hacker_red = '#8A2323'
hacker_red_bright = '#AC4545'
hacker_comment = '#3A5A3A'
hacker_accent1 = '#008A00'
hacker_accent2 = '#3080A0'

[os]
disabled = false
style = "fg:hacker_bg"
format = "$symbol "

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
Macos = "󰀵"
Linux = "󰌽"
Alpine = ""
Amazon = ""
Arch = "󰣇"
CentOS = ""
Debian = "󰣚"

[username]
show_always = true
style_user = "fg:hacker_bg"
style_root = "fg:hacker_bg"
format = "$user "

[directory]
style = "fg:hacker_fg"
format = "$path "
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
disabled = false
symbol = ""
style = "fg:hacker_fg"
format = "$symbol $branch "

[git_status]
disabled = false
style = "fg:hacker_yellow"
format = "$all_status "
stashed = "$"
ahead = "↑"
behind = "↓"
diverged = "↕"
conflicted = "fg:hacker_red bold"
deleted = "✘"
renamed = "»"
modified = "*"
staged = "+"
untracked = "*"

[nodejs]
symbol = ""
style = "fg:hacker_fg"
format = "$symbol ($version) "

[c]
symbol = " "
style = "fg:hacker_fg"
format = "$symbol ($version) "

[rust]
symbol = ""
style = "fg:hacker_fg"
format = "$symbol ($version) "

[golang]
symbol = ""
style = "fg:hacker_fg"
format = "$symbol ($version) "

[php]
symbol = ""
style = "fg:hacker_fg"
format = "$symbol ($version) "

[java]
symbol = " "
style = "fg:hacker_fg"
format = "$symbol ($version) "

[kotlin]
symbol = ""
style = "fg:hacker_fg"
format = "$symbol ($version) "

[haskell]
symbol = ""
style = "fg:hacker_fg"
format = "$symbol ($version) "

[python]
symbol = ""
style = "fg:hacker_fg"
format = "$symbol ($version) "

[docker_context]
symbol = ""
style = "fg:hacker_fg"
format = "$symbol ($context) "

[time]
disabled = false
time_format = "%R"
style = "fg:hacker_fg"
format = " $time "

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:hacker_green)'
error_symbol = '[](bold fg:hacker_red)'
vimcmd_symbol = '[▶](bold fg:hacker_green)'
vimcmd_replace_one_symbol = '[◆](bold fg:hacker_green_bright)'
vimcmd_replace_symbol = '[◇](bold fg:hacker_green_bright)'
vimcmd_visual_symbol = '[■](bold fg:hacker_yellow)'
